### ISSUE TITLE
Misspellings

### ISSUE THREAD

**Issue by starlightromero** [Make-School-Labs/web-assessment#1]
### Greeting Make School

There are a few misspellings that may affect the users' understanding. They are italicized below.

*too*
`
If you don’t, or this challenge is way to difficult, that is OKAY.
`

*be completed wholley*
`
You won't use any libraries or frameworks for this project. It should completed wholey with vanilla HTML, CSS, and JS.
`

*solved*
`
The whole problem should *saolved* with HTML elements, CSS, and JavaScript.
`

I **appreciate** all of you for putting this assessment together. Here's to a great school year!

**Comment by ibirnam** [comment]
Thanks @starlightromero ! Fixed in the latest commit, looking forward to meeting you!
